### ISSUE TITLE
Allow negative flatmates during signup

### ISSUE THREAD

**Issue by finn-stainton** [SDP-Flinder/flinder-react#29]
**Describe the bug**
During signup, the user is able to enter a negative number of flatmates

**To Reproduce**
1. Goto /register
2. Fill in the forms until you get to flat information
3. Enter a negative number in the "number of flatmates" field. 
4. Submit the form

**Expected behavior**
Expect to receive a warning explaining no negative numbers allowed and unable to submit

**Screenshots**
![image](https://user-images.githubusercontent.com/10103221/136756329-8b38ec81-d244-4191-a6f1-42f2bfdf02c0.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox

**Comment by danieltran-512** [comment]
Fixed
